sm8250-common: vibrator: Include missing fcntl.h
* Fix the following errors

device/xiaomi/gauguin/vibrator/Vibrator.cpp:103:50: error: use of undeclared identifier 'O_RDWR'
        fd = TEMP_FAILURE_RETRY(open(devicename, O_RDWR));
                                                 ^
device/xiaomi/gauguin/vibrator/Vibrator.cpp:103:50: error: use of undeclared identifier 'O_RDWR'
device/xiaomi/gauguin/vibrator/Vibrator.cpp:103:14: error: assigning to 'int' from incompatible type 'void'
        fd = TEMP_FAILURE_RETRY(open(devicename, O_RDWR));
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bionic/libc/include/unistd.h:306:33: note: expanded from macro 'TEMP_FAILURE_RETRY'
                                ^~~~~~~~~~~~
device/xiaomi/gauguin/vibrator/Vibrator.cpp:333:46: error: use of undeclared identifier 'O_RDWR'
    fd = TEMP_FAILURE_RETRY(open(devicename, O_RDWR));
                                             ^
device/xiaomi/gauguin/vibrator/Vibrator.cpp:333:46: error: use of undeclared identifier 'O_RDWR'
device/xiaomi/gauguin/vibrator/Vibrator.cpp:333:10: error: assigning to 'int' from incompatible type 'void'
    fd = TEMP_FAILURE_RETRY(open(devicename, O_RDWR));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bionic/libc/include/unistd.h:306:33: note: expanded from macro 'TEMP_FAILURE_RETRY'
                                ^~~~~~~~~~~~
device/xiaomi/gauguin/vibrator/Vibrator.cpp:346:40: error: use of undeclared identifier 'O_WRONLY'
    fd = TEMP_FAILURE_RETRY(open(file, O_WRONLY));
                                       ^
device/xiaomi/gauguin/vibrator/Vibrator.cpp:346:40: error: use of undeclared identifier 'O_WRONLY'
device/xiaomi/gauguin/vibrator/Vibrator.cpp:346:10: error: assigning to 'int' from incompatible type 'void'
    fd = TEMP_FAILURE_RETRY(open(file, O_WRONLY));
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bionic/libc/include/unistd.h:306:33: note: expanded from macro 'TEMP_FAILURE_RETRY'
                                ^~~~~~~~~~~~
9 errors generated.

Signed-off-by: Molyuu <mi@molyuu.cyou>